<a href="https://colab.research.google.com/github/varadmahatme/Advanced-machine-learning-deep-learning/blob/main/AMLDL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1+4

In [ ]:
5**7

In [ ]:
5^7

In [ ]:
25**(1/2)

In [ ]:
1e2

In [ ]:
2.7*2

In [ ]:
a=26
print(a)

In [ ]:
var1=40

In [ ]:
var2=var1+100

In [ ]:
print(var2)

In [ ]:
side=1726
area=side*side
print('Area of a square=')
print(area)

In [ ]:
side=5
area=side**2
print("Area=", area)

In [ ]:
# A code to find the area of a square
 
side=input('Enter a value of side:')
print(type(side))
side=int(side)
print(type(side))
area=side*side
print('Area is:',area)

In [ ]:
# A code to find the area of a square
side=input('Enter a value of side:')
print(type(side))
side=int(side)
print(type(side))
area=side*side
print('Area is:',area)

In [ ]:
'i'm an engineer'

In [ ]:
var1=3

In [ ]:
var2=var1+100 +2


In [ ]:
print(str)

In [ ]:
R_no=100
emp_name='Rahul'

In [ ]:
print('My Roll No. is {​​​​​​one}​​​​​​, and my name is {​​​​​​two}​​​​​​'.format(one=R_no,two=emp_name))

In [ ]:
print('My Roll No. is: {​​​​​​}​​​​​​, and my name is: {​​​​​​}​​​​​​'.format(R_no,emp_name))

In [ ]:
emp_name='s'+emp_name[1:5]

In [ ]:
print(emp_name)

In [ ]:
emp_name*5

In [ ]:
emp_name.upper()

In [ ]:
s='Good Morning Everone'

In [ ]:
s1,s2,s3=s.split()
print(s1)
print(s2)
print(s3)

In [ ]:
print(s.split('E'))

In [ ]:
print("hello everyone \n Good day \t nice time")

In [ ]:
emp_name[::3]

In [ ]:
emp_name[3::]

In [ ]:
emp_name[::-1]

In [ ]:
emp_name[::-2]

In [ ]:
emp_name[::-3]

In [ ]:
list='1,2,3,bro,varad'

In [ ]:
list

In [ ]:
print(list1=[1,3,5,bro,varad,mahatme,8.3])

In [ ]:
list1=[1,3,5,'bro','varad','mahatme',8.3]

In [ ]:
print(list1)

In [ ]:
list_new=[200,500,6.9,list1]

In [ ]:
print(list_new)

In [ ]:
list_new[0:2]

In [ ]:
list_new.pop(1)

In [ ]:
print(list_new)

In [ ]:
# to reverse a list use 'reverse' command
list1 = ['programming', 91, [2, 17, 22], 'practice']
list1.reverse()
print ("list now : ", list1)

In [ ]:
len(list1)

In [ ]:
list1

In [ ]:
list1=[10,5,'ab',2e-4]

In [ ]:
list1[1]

dictionary

In [ ]:
dictionary1={10:11,11:12,12:13,13:14}

In [ ]:
print(dictionary1)

In [ ]:
dictionary1[12]

In [ ]:
dict={5:25,6:50,7:'brother'}

In [ ]:
dict[7]

In [ ]:
d_1={'k1':True, 'k2':False}

In [ ]:
d_1['k1']

In [ ]:
print(d_1['k1'])

In [ ]:
dict_two={'key1':10,'key2':4.9,'key3':[3,8],'key4':dict}

In [ ]:
dict_two['key4']

In [ ]:
dict_two['key3']

In [ ]:
dict_two={'key1':10,'key2':4.9,'key3':list(range(3,8,2)),'key4':dict}

In [ ]:
dict_two['key4']

In [ ]:
dict_two['key3']

In [ ]:
dict_3={}

In [ ]:
dict_3['key1']=10

In [ ]:
dict_3

In [ ]:
print(dict_two.keys())

In [ ]:
print(dict_two.values())

In [ ]:
list3=list(dict_two.keys())

In [ ]:
print(list3)

In [ ]:
print(dict_two.items())

In [ ]:
11==10

In [ ]:
3>5

In [ ]:
5>1

In [ ]:
tup_1=(20,5)

In [ ]:
print(tup_1)

In [ ]:
tup_1[1]=100

In [ ]:
tup_1.append(3)

In [ ]:
tup2=(10, 20, 'note', 6.2,100, 20,'book',[2,3,5])

In [ ]:
print(tup2[6])

In [ ]:
tup2.index(6.2)

In [ ]:
tup2.index(20)

In [ ]:
tup2.count(20)

In [ ]:
set1=(100)
print(set1)
set1.add(20)
set1.add(40)
print(set1)
set1.add(70)
print(set1)

In [ ]:
set1=(100)
print(set1)
set1.add(20)
set1.add(40)
print(set1)
set1.add(70)
print(set1)

In [ ]:
a='abc'
print(a)

In [ ]:
print(type(a))

In [ ]:
num1=None

In [ ]:
print(type(num1))

In [ ]:
10.5 and (1>2)

In [ ]:
a=20
if(a>10):
  print(a)
  print(a+5)

In [ ]:
a=100
if (a==100):
  print("Greetings")

In [ ]:
x=30
if(x==30):
  print('Number is 30')
else:
  print('Number is not 30')
print('ok')

In [ ]:
z=int(input('enter value:' ))
if(z>0):
  print('positive number')
if(z<0):
  print('negetive number')
if(z==0):
  print('zero')

In [ ]:
x=20<10
if x:
  print('this is executed')
else:
  print('this is executed bro')

In [ ]:
list = []

# number of elements as input
n = int(input("Enter number of elements : "))

# iterating till the range
for i in range(0, n):
  ele = int(input())

  list.append(ele) # adding the element
  
print(list)

target = int(input("enter the target number")) 
for i in range(len(list)):
    num = target-list[i]
    for j in range(i+1, len(list)):
        if list[j] == num:
            print (list[i], list[j])


In [ ]:
#while lool

i=1

while(i<=10):
    print(i)
    i=i+1


In [ ]:
#range function

list(range(1,16,1))

In [ ]:
list(range(1,16,3))

In [ ]:


list(range(15,0,-1))

In [ ]:
#range function

list(range(10,1,-1))

in python everything is an object

In [ ]:
list1=list(range(100,69,-4))

In [ ]:
print(list1)
for i in list1:
  print(str(i)+" UBER")

In [ ]:
for i in 'VARAD MAHATME':
  print(i)

In [ ]:
a=int(input("enter number to convert to a table"))
for i in range(1,11,1):
  print(a,"x",i,"=",a*i)

In [ ]:
#cube & cube root of nos from 1 to 100
for i in range(1,101,1):
  print("number=",i,"cube is ",i**3,"cube root is ",i**(1/3))

In [ ]:
i2=range(1,10,1)
for i in i2:
  print(i**3)

In [ ]:
#by default dict will print keys in stead of value
dict1={'key1':100,'key2':12,'key3':42}
for i in dict1:
  print(i)

In [ ]:
#by default dict will print keys in stead of value
dict1={'key1':100,'key2':12,'key3':42}
for i in dict1:
  print(dict1[i])

In [ ]:
#print only numbers divisible by 2 in a list
list2=[101,102,55,56,4,8,13,18]
for i in list2:
  if i%2==0:
    print(i)

In [ ]:
#creating a function in python
#functions are defined and called within a main program

def find_area(b,h):
  area_1=b*h
  return area_1

In [ ]:
#calling function
num1= int(input("enter b"))
num2= int(input("enter h"))
var1=find_area(num1,num2)
print(var1)

In [ ]:
# def keyword is used to define a function
import math
def area_of_circle(radius):
    Area_circ= math.pi* radius * radius
    return Area_circ

r1 =input("Enter a radius value:")

r1_num=float(r1)

Val_from_fn = area_of_circle(r1_num)
print("The Area of circle is {}".format(Val_from_fn))


In [ ]:
import math
def perimeter(radius):
  peri=2*math.pi*radius
  return peri

rad=float(input("enter the raius value: "))

val_peri=perimeter(rad)
print(val_peri)



In [ ]:
import math
print(math.pi)

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
list_1=[3,4,5,6]
x=np.array(list_1)
type(x) #Data type of python is different than numpy. List in python, ndarray in numpy. 

In [ ]:
# Generation of numpy using built in techniques
np_arr=np.arange(3,6,2)
print(np_arr)

In [ ]:
import numpy as np
np_arr1=np.ones(5,dtype='float32')
print(np_arr1)
type(np_arr1)

In [ ]:
#LINKED LISTS

# A simple Python program to introduce a linked list

# Node class
class Node:

	# Function to initialise the node object
	def __init__(self, data):
		self.data = data # Assign data
		self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

	# Function to initialize head
	def __init__(self):
		self.head = None


# Code execution starts here
if __name__=='__main__':

	# Start with the empty list
	llist = LinkedList()

	llist.head = Node(1)
	second = Node(2)
	third = Node(3)

	'''
	Three nodes have been created.
	We have references to these three blocks as head,
	second and third

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | None |	 | 2 | None |	 | 3 | None |
	+----+------+	 +----+------+	 +----+------+
	'''

	llist.head.next = second; # Link first node with second

	'''
	Now next of first Node refers to second. So they
	both are linked.

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | o-------->| 2 | null |	 | 3 | null |
	+----+------+	 +----+------+	 +----+------+
	'''

	second.next = third; # Link second node with the third node

	'''
	Now next of second Node refers to third. So all three
	nodes are linked.

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | o-------->| 2 | o-------->| 3 | null |
	+----+------+	 +----+------+	 +----+------+
	'''



In [ ]:
# A simple Python program for traversal of a linked list

# Node class
class Node:

	# Function to initialise the node object
	def __init__(self, data):
		self.data = data # Assign data
		self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

	# Function to initialize head
	def __init__(self):
		self.head = None

	# This function prints contents of linked list
	# starting from head
	def printList(self):
		temp = self.head
		while (temp):
			print (temp.data)
			temp = temp.next


# Code execution starts here
if __name__=='__main__':

	# Start with the empty list
	llist = LinkedList()

	llist.head = Node(1)
	second = Node(2)
	third = Node(3)

	llist.head.next = second; # Link first node with second
	second.next = third; # Link second node with the third node

	llist.printList()



In [ ]:
import numpy as np

In [ ]:
#generation of numpy array from python lists
list_1=[10,2,35,40]

In [ ]:
type(list_1)

In [ ]:
type(list_1[0])

In [ ]:
np.ndarray

In [ ]:
list_2=[[1,4],[-8,3]]

In [ ]:
np.array(list_2)

array([[ 1,  4],
       [-8,  3]])

In [ ]:
type(list_2[0])

list

In [ ]:
list_3=[[1,4,2],[-8,3,4],[2,6,9]]

In [ ]:
#arange is the command is used for creating arrays using built in techniques
np_arr1=np.arange(3,6,2)

In [ ]:
print(np_arr1)

[3 5]


In [ ]:
np_arr1=np.arange(1,6,3)
print(np_arr1)

[1 4]


In [ ]:
import numpy as np
np_arr2=np.ones(5,dtype='int32') # vector 1-D
print(np_arr2)

[1 1 1 1 1]


In [ ]:
np_arr3=500*np.ones(10,dtype='int32')
print(np_arr3)

[500 500 500 500 500 500 500 500 500 500]


In [ ]:
np_arr3=np.ones((32,35),dtype='int32')
print(np_arr3)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [ ]:
np_arr4=np.zeros(9)
print(np_arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np_arr4=np.zeros(9,dtype='int32')
print(np_arr4)

[0 0 0 0 0 0 0 0 0]


In [ ]:
np_arr6=np.linspace(1,10,3)
print(np_arr6)

[ 1.   5.5 10. ]


In [ ]:
np_arr6=np.linspace(2,10,4)
print(np_arr6)

[ 2.          4.66666667  7.33333333 10.        ]


In [ ]:
np_arr7=np.eye(3)
print(np_arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np_arr8=np.random.rand(4) #span from [0,1]
print(np_arr8)

[0.94433989 0.50347672 0.22275706 0.74583124]


In [ ]:
np_arr8=np.random.randn(4) #span from [0,1]
print(np_arr8)

[-0.65741376 -1.01339956  1.02249372 -1.48652634]


In [ ]:
np_arr9=np.random.rand(4,5)
print(np_arr9)

[[0.79788724 0.9966841  0.39253259 0.69357194 0.20212428]
 [0.59813056 0.09808028 0.14782364 0.94415527 0.22897949]
 [0.68890322 0.18502984 0.68038512 0.81330516 0.14752695]
 [0.5890465  0.63195151 0.47802942 0.20657225 0.48025111]]


In [ ]:
np_arr9.reshape(2,10)

array([[0.79788724, 0.9966841 , 0.39253259, 0.69357194, 0.20212428,
        0.59813056, 0.09808028, 0.14782364, 0.94415527, 0.22897949],
       [0.68890322, 0.18502984, 0.68038512, 0.81330516, 0.14752695,
        0.5890465 , 0.63195151, 0.47802942, 0.20657225, 0.48025111]])

In [ ]:
y=np_arr9.reshape(4,5)
print(y)

[[0.79788724 0.9966841  0.39253259 0.69357194 0.20212428]
 [0.59813056 0.09808028 0.14782364 0.94415527 0.22897949]
 [0.68890322 0.18502984 0.68038512 0.81330516 0.14752695]
 [0.5890465  0.63195151 0.47802942 0.20657225 0.48025111]]


In [ ]:
print(np_arr9.max()) #value

0.996684099594939


In [ ]:
print(np_arr9.argmax()) #position

1


In [ ]:
type(np_arr9.shape)

tuple

In [ ]:
np_arr9.dtype

dtype('float64')

In [ ]:
np_arr9>0.2

array([[ True,  True,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [ ]:
!pip install scipy

In [ ]:
import numpy as np
from scipy import linalg
numpy_mat=np.array([[3,2,2],[5,5,2],[7,8,69]])
linalg.det(numpy_mat)

335.00000000000006

In [ ]:
EW, EV = linalg.eig(numpy_mat)
print(EW)
print('\n')
print(EV)

[69.48501546+0.j  0.70830143+0.j  6.80668311+0.j]


[[-0.03105513 -0.64577793 -0.39161821]
 [-0.03339063  0.76317248 -0.90600067]
 [-0.99895978 -0.0232083   0.16061746]]


In [ ]:
from numpy import poly1d
p = poly1d([5,3,2,1])
print(p)

   3     2
5 x + 3 x + 2 x + 1


In [ ]:
print(p.deriv()) # derivative of above polynomial

    2
15 x + 6 x + 2


In [ ]:
#Computation of FFT
from scipy.fftpack import fft,ifft
import numpy as np
#Numpy array generation
x = np.array([1.0, 1.0, 1.0, 1.0])

#Applying the fft function
y = fft(x)
print(y)

[4.-0.j 0.+0.j 0.-0.j 0.-0.j]


In [ ]:
yinv = ifft(y)
print(yinv)

[1.+0.j 1.+0.j 1.-0.j 1.+0.j]


In [2]:
#pandas
#used for data analysis & visualization
!pip install pandas


In [3]:
%matplotlib inline
import pandas as pd

In [4]:
df = pd.DataFrame({'Marks':[None,55,66,46,34,22,18,55],'Name':['def','pqr','gpi','xyz','abc','ccv','otp','por']})
df.head() #will show first 5 rows

Marks Name
0    NaN  def
1   55.0  pqr
2   66.0  gpi
3   46.0  xyz
4   34.0  abc

In [5]:
df = pd.DataFrame({'Marks':[None,55,66,46,34,22,18,55],'Name':['def','pqr','gpi','xyz','abc','ccv','otp','por']})
df

Marks Name
0    NaN  def
1   55.0  pqr
2   66.0  gpi
3   46.0  xyz
4   34.0  abc
5   22.0  ccv
6   18.0  otp
7   55.0  por

In [6]:
print(df.to_string()) #better way

   Marks Name
0    NaN  def
1   55.0  pqr
2   66.0  gpi
3   46.0  xyz
4   34.0  abc
5   22.0  ccv
6   18.0  otp
7   55.0  por


In [8]:
df['Marks'].value_counts() #shows how many times a number has appeared

55.0    2
66.0    1
46.0    1
34.0    1
22.0    1
18.0    1
Name: Marks, dtype: int64

In [10]:
df['Marks']

0     NaN
1    55.0
2    66.0
3    46.0
4    34.0
5    22.0
6    18.0
7    55.0
Name: Marks, dtype: float64

In [11]:
df['Name'].value_counts()

def    1
pqr    1
gpi    1
xyz    1
abc    1
ccv    1
otp    1
por    1
Name: Name, dtype: int64

In [12]:
df['Name'].nunique()


8

In [14]:
df['Marks'].nunique() #shows the number of only unique elements

6

In [16]:
ans_arr=df['Name'].unique()
print(ans_arr)

['def' 'pqr' 'gpi' 'xyz' 'abc' 'ccv' 'otp' 'por']


In [17]:
ans_arr.dtype

dtype('O')

In [18]:
df


Marks Name
0    NaN  def
1   55.0  pqr
2   66.0  gpi
3   46.0  xyz
4   34.0  abc
5   22.0  ccv
6   18.0  otp
7   55.0  por

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Marks   7 non-null      float64
 1   Name    8 non-null      object 
dtypes: float64(1), object(1)
memory usage: 256.0+ bytes


In [20]:
df.describe('')

Marks
count   7.000000
mean   42.285714
std    18.117342
min    18.000000
50%    46.000000
max    66.000000

In [21]:
# selection of data from dataframe
df_2=df[df['Marks']>50]
print(df_2)

   Marks Name
1   55.0  pqr
2   66.0  gpi
7   55.0  por


In [22]:
def pract_marks(data1):
    return data1+5


df_3=df['Marks'].apply(pract_marks)
df_3 #marks increased by 5

0     NaN
1    60.0
2    71.0
3    51.0
4    39.0
5    27.0
6    23.0
7    60.0
Name: Marks, dtype: float64

In [23]:
df_3.head()

0     NaN
1    60.0
2    71.0
3    51.0
4    39.0
Name: Marks, dtype: float64

In [24]:
df_2 #previous index remains

Marks Name
1   55.0  pqr
2   66.0  gpi
7   55.0  por

In [25]:
df.columns

Index(['Marks', 'Name'], dtype='object')

In [26]:
df.sort_values(by='Name')

Marks Name
4   34.0  abc
5   22.0  ccv
0    NaN  def
2   66.0  gpi
6   18.0  otp
7   55.0  por
1   55.0  pqr
3   46.0  xyz

In [27]:
df.isnull()

Marks   Name
0   True  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False

In [28]:
from numpy.random import randn
df = pd.DataFrame(randn(4,4),index='e1 e2 e3 e4'.split(),columns='f1 f2 f3 f4'.split())
df

f1        f2        f3        f4
e1 -0.533225  0.592447  0.501065 -0.121257
e2 -0.821765 -0.954368  0.458042  1.062357
e3  2.231982 -0.263151  1.325541 -0.484753
e4  1.743792 -0.252169  0.916030 -1.341500

In [29]:
df[['f3','f4']]

f3        f4
e1  0.501065 -0.121257
e2  0.458042  1.062357
e3  1.325541 -0.484753
e4  0.916030 -1.341500